### ISSUE TITLE
Add functionality to support Pushbullet Channels

### ISSUE THREAD

**Issue by mikebirdgeneau** [eddelbuettel/rpushbullet#18]
Refer to 57ebf5084f6eb52a43342cf5ffe3c7b30a202d7a for an update to documentation describing how to create channels for Pushbullet, and a brief reference to the Pushbullet API and the target parameter `channel_tag` which allows the target channel to be specified for a push.

**Comment by eddelbuettel** [comment]
Hi @mikebirdgeneau -- Happy New year!

I guess the holidays/new year got in the way.  Shall we resume testing this?

**Comment by mikebirdgeneau** [comment]
Hi @eddelbuettel - Happy new year to you as well. I found myself quite busy with my day job! 
Anyhow, I've taken a quick stab at the changes in order above, using your suggestion of messaging > email > channel. 

For testing, we may be able to use the JSON results to develop logic to ensure that tests pass as intended. Do you have any good examples of where you perform tests for another package that might be a good template to follow? 

All changes are in my fork here:
https://github.com/mikebirdgeneau/rpushbullet/compare/eddelbuettel:master...master

I'll create a pull request to review and discuss the changes.

**Comment by eddelbuettel** [comment]
Thanks so much -- looks really promising so far.

**Comment by eddelbuettel** [comment]
I added some support in R/init.R.  Now we can have test email and channel targets. 

However, it looks like broke/lost some functionality.  Very first test:

```{r}
R> pbPost("note", "A Simple Test", "We think this should work.\nWe really do.")
Error in FUN(""[[1L]], ...) : 
  argument "email" is missing, with no default
R> 
```

**Comment by mikebirdgeneau** [comment]
I've updated the tests to use those variables you've added and submitted a pull request (#21). 
Everything seems to run successfully for me now, so if your problem persists we can debug.

**Comment by eddelbuettel** [comment]
Awesome. I spent most of yesterday with Rcpp* so I did not get to it.

I think I'll rewrite tests/simpleTests.R as a caller to 'normal' unit tests, that way we can spread out the combinations of type and recipient.   OK if I use RUnit which has been reliable for me in the past?

**Comment by mikebirdgeneau** [comment]
I've never used RUnit, so I'm happy to follow your lead on this! 
Aside: just received a push from you.

**Comment by eddelbuettel** [comment]
Yes, sorry -- just replaced your remaining test email and channel settings.   

I think I fixed why the first call in the test script failed, we tested `email` for `NA` but had set it to `''`. Doh.

**Comment by eddelbuettel** [comment]
Just committed -- give it a whirl when you have moment.

**Comment by eddelbuettel** [comment]
Ok, I no longer think we have to go to RUnit.  So no rush there.

But you had made some comments days ago about a README (or Rd file?) needing to change once we have channels.  As channels now work,  a) what is that edit, and b) shall we make it?

**Comment by mikebirdgeneau** [comment]
Everything seems to be working for me at the moment. 
Readme.md changes are just updating to say that channels can be used in the package. I've made the change in this commit: 
https://github.com/mikebirdgeneau/rpushbullet/commit/7614a7d36ef0cb9b23907efefc6ea6c679b0f556

**Comment by eddelbuettel** [comment]
Ok, great -- as this wasn't a PR I just took it by hand.  Will do the same with technically open PR and then close it, ok?
