### ISSUE TITLE
Switch to jsonlite?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rpushbullet#31]
Tried switching from (old) RJSONIO to (newer) jsonlite but simpleTests.R balks on file upload.

@restonslacker Can you take a peek?  It is curl/jsonlite interaction. Somehow the token gets lost.

**Comment by restonslacker** [comment]
it appears that RJSONIO and jsonlite didn't quite align at how to unnest a single object.  RSJONIO returned a vector with a single character and jsonlite was returning a list with a single string.  that solved the issue for me.

**Comment by eddelbuettel** [comment]
I looked at it, suspecting such a minor difference, but somewhat I was too dense.  Or had too little coffee.

**Comment by restonslacker** [comment]
given that it took me 5 commits to make that change, i'd say you're not alone.
