### ISSUE TITLE
summary.pbDevices is broken

### ISSUE THREAD

**Issue by restonslacker** [eddelbuettel/rpushbullet#42]
```R
summary(pbGetDevices())
```
>Pushbullet device summary for 16 devices with these ids:
> NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  NA  

the `devices` data.frame in the object returned by `pbGetDevices` has 16 columns, but in my case only 5 devices/rows.  This was introduced after 0.2.0.  will submit a PR

**Comment by restonslacker** [comment]
Actually, I don't want to make the commit tree too messy again.  Is it better to wait until #41 is resolved, pull master and then cut a branch with the fix or should i cut a branch now and then merge master into it #41 is merged but before this PR is merged?

**Comment by eddelbuettel** [comment]
Sure.  One step at a time is fine and more measured.  We're in no rush.

**Comment by eddelbuettel** [comment]
Done in #43
