### ISSUE TITLE
Can't post in non-interactive session on remote server

### ISSUE THREAD

**Issue by rensa** [eddelbuettel/rpushbullet#46]
RPushbullet is working fantastically for me, but a prime use-case for me is to find out when scripts that I run non-interactively finish.

Testing a simple script out locally with Rscript works fine:

    $ cat test.r 
    #!/usr/bin/env Rscript
    
    library(RPushbullet)
    pbPost('note', title = 'Title yo', body = 'And also a body')
    message('All done')
    
    
    $ ./test.r 
    Attaching RPushbullet version 0.3.1.
    Reading ~/.rpushbullet.json
    All done

But when I log onto my work computer and submit a shell script that runs this via Rscript to the queue, it returns an error from `pbPost()`:

    All done! Merging and pushing the logs
    Error in curl::curl_fetch_memory(pburl, handle = h) :
      Couldn't resolve host name
    Calls: pbPost ... lapply -> FUN -> .createPush -> <Anonymous> -> .Call

If I open an interactive R session on this computer, I can push without a problem.

**Comment by eddelbuettel** [comment]
> But when I log onto my work computer and submit a shell script that runs this via Rscript to the queue

What if you try to that straight in R, foregoing the shell script?

> `Couldn't resolve host name`

That more or less points to a setup issue at your end I fear.

**Comment by rensa** [comment]
@eddelbuettel Seems to work fine when I directly execute `Rscript test.r`. It seems like maybe an environment problem to do with the queueing system?

**Comment by eddelbuettel** [comment]
You said the same thing twice now: from the command-line it works.

You also said it fails _if you call to shell from R_ to which I replied that you can call R in R.  So can you do that, please?

I have no idea what "queueing system" you refer to.

**Comment by eddelbuettel** [comment]
We do test RPushbullet quite a bit, even on Travis. So if it fails for you, maybe something is different at your side?

**Comment by rensa** [comment]
I can open R interactively and `pbPost()` from there. I can also `pbPost()` from a script that is called by Rscript from bash. What I can't do is call Rscript from a shell script, as required by [this scheduling system](https://opus.nci.org.au/display/Help/How+to+use+PBS) on my system for jobs beyond certain resource limits.

I don't mean to come off accusatory—I'm not suggesting that this is necessarily a problem with RPushbullet! Just that I'm having an issue and I'm hoping you might be able to help me resolve it.

**Comment by eddelbuettel** [comment]
Right. So now we know it is PBS.  Which I don't have access to.

It may come down to you painstakenly comparing `env` in your standard shell and what you get under PBS.  Something will be different.   

I will leave this open but I have the feeling (which could well be misplaced) that this has nothing to do with the RPushbullet code.

**Comment by rensa** [comment]
I've verified that Internet access is blocked on most job queues for PBS on my system. I'll instead use email notifications and [IFTTT](ifttt.com) to get dinged ;)

Thanks very much for your patience!
