### ISSUE TITLE
Should error when missing title or body (or at least give a helpful message)

### ISSUE THREAD

**Issue by MichaelChirico** [eddelbuettel/rpushbullet#49]
I think there was a change in the interface to `pbPost` (somewhat expected for such a new package), so that my older code stopped working:

```
library(RPushbullet)
pbPost('note', 'Code done!')
```
> Warning message:
400: Bad Request - Usually this results from missing a required parameter. 

It took quite a while to figure out what was going on (both `body` and `title` are required here) -- `debug = TRUE` wasn't helpful either, it wasn't until I manually inspected the `ret` object that I figured out what's going on.

Probably should have errored before attempting the request. Is `''` a useful default for `title`/`body` if it's leading to errors like this?

**Comment by eddelbuettel** [comment]
[Minimally reproducible example or it doesn't exist](https://stackoverflow.com/help/mcve)

**Comment by eddelbuettel** [comment]
Keep in mind that we _multiple_ message types some of which have different argument sets.

**Comment by MichaelChirico** [comment]
@eddelbuettel sorry I hit enter before typing the request

**Comment by restonslacker** [comment]
@MichaelChirico we had a  discussion about errors versus warnings (#29)

> warning() seems better. Users can then decide if they want "warnings-as-error" which R supports.

Also part of the reason for this from my perspective is that if I'm running a long job, i'm generally using RPusuhbullet for notifications about the status.  I don't want to terminate my job early because there was a problem with RPushbullet since it's secondary to my main purpose.

The actual text of those warnings is taken straight from the Pushbullet API docs. https://docs.pushbullet.com/#http-status-codes

**Comment by restonslacker** [comment]
Also, having just run your test now, it appears to be working.  Perhaps your credentials for the Pushbullet service are not correct?

**Comment by eddelbuettel** [comment]
But I think @MichaelChirico is correct that in 

```r
R> library(RPushbullet)       # lowercase b
Attaching RPushbullet version 0.3.1.
Reading ~/.rpushbullet.json
R> pbPost(type="note", title="test", body="body")
R> pbPost(type="note", title="test", body="")
R> pbPost(type="note", title="test")
Warning message:
400: Bad Request - Usually this results from missing a required parameter. 
R> 
```

only the first two send something. Which may be new.  If body is `" "` instead of `""`, messages go through.  That does however seem to be caused at _their backend_ and is not filtered on our side.

**Comment by restonslacker** [comment]
Concur that this is on their end.  I've tested this several times this morning and `pbPost('note', 'Code Done!')` was working for me until just now (and I changed no code in the interim).  

I would be okay with defaulting `body` to a single space (i.e. `body=' '`) if there is consensus that this would be an expedient way to resolve the issue associate with this change on Pushbullet's end.  I think that it is unlikely to break any scripts where a body was left unspecified whereas making an error for an empty body certainly would.  We could issue a warning saying that both body and title are required for notes, but I feel like that adds friction for existing users.  The only other solution that comes to mind while typing this is to copy the title into the body in the cases when the user hasn't specified a body.  Of all of these, I think my preference is for the first, but that's based on how I use the service.

thoughts?

**Comment by eddelbuettel** [comment]
I am of two minds here.  It is annoying that it currently does not send with an empty string body.  I am however quite reluctant to make a fix of adding a single space -- that seems silly.

At the end of the day this is still mostly user error.  A fully qualified note needs title and body.

**Comment by MichaelChirico** [comment]
I understand `body = ' '` is a bit duct-tapey. What about at least being more helpful if `debug = TRUE` is on?

**Comment by eddelbuettel** [comment]
You have not really made clear why you can't set all three of type, title and body.

**Comment by MichaelChirico** [comment]
I can (and updated my code so that I do), but that doesn't obviate the need for helpful errors & warnings. There's also nothing in the documentation about the need for non-empty `title` and `body` for `type = 'note'`. 

It also strikes me as silly to be sending known-erroneous posts to the API.
