### ISSUE TITLE
Secure testing of PR

### ISSUE THREAD

**Issue by csgillespie** [eddelbuettel/rpushbullet#51]
Following #50, here's a route to secure testing of a PR.

1. Create two environment keys in travis (under [settings](https://travis-ci.org/eddelbuettel/rpushbullet/settings))
  * `key`
 * `device`

2. Alter your test file to create the necessary json file, e.g. https://github.com/csgillespie/rpushbullet/blob/master/tests/simpleTests.R

3. On line 11 of the simpleTests.R script I've included `message(json)` to peak at the api key. This doesn't 
work (https://travis-ci.org/csgillespie/rpushbullet#L1341)

4. I suspect you can remove all instances of Sys.getenv("Run_RPushbullet_Tests_All") in your files
---

I would submit a PR, but you use a homebrew version of .travis.yml and you still need to add your API keys to travis. 

Hope that's clear.

**Comment by eddelbuettel** [comment]
This got stale.  Was there something left we wanted to do?

**Comment by csgillespie** [comment]
If I remember, this issue arose because pushbullet can't run travis on a PR due to API keys. Not sure if you've fixed this or not.

**Comment by eddelbuettel** [comment]
No, it still only runs in master but that is fine by me (as it is somewhat annoying to have all the windows pop here when Travis runs ;-) ).  Nothing urgent,

**Comment by csgillespie** [comment]
Looking at your travis file, you could [simplify](https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches) it via
```
# Only run on master
branches:
  only:
  - master
 ```

**Comment by eddelbuettel** [comment]
But that is already the status quo :)  So what would we gain? Simply be more explicit?

**Comment by csgillespie** [comment]
More explicit; also if you ever needed to do something similar again.

**Comment by eddelbuettel** [comment]
Maybe I am dense but if I add

```
# and only run this on master
branches:
  only:
  - master
```

won't all of Travis then be turned off for PRs?  Which is, arguably, worse than status quo?

**Comment by csgillespie** [comment]
Yes that's correct - travis will be turned off on all PRs

I suppose I don't understand what you are using travis for on PR.

**Comment by eddelbuettel** [comment]
The set of 'things' checked by `R CMD check` is larger than the subset running actually executed tests.  I enjoy having the remainder being executed for me.
