### ISSUE TITLE
pbSetup: load token

### ISSUE THREAD

**Issue by csgillespie** [eddelbuettel/rpushbullet#52]
On the initial set-up using `pbSetup()` the key is forgotten. 

 * Proposal: after running `pbSetup()` load the key using the same mechanism as `library(RPushbullet)` uses
Happy to submit a PR

---

Example:

```
library(RPushbullet)
#Attaching RPushbullet version 0.3.1.
# No file ~/.rpushbullet.json found. Consider
pbSetup("XXX")
pbPost("note", "test")
# Error: Neither option 'rpushbullet.key' nor entry in package environment found. Aborting
```
Restarting R
```
library(RPushbullet)
pbPost("note", "test")
```
now works

**Comment by eddelbuettel** [comment]
Interesting.  Clearly an overisght.  

A nice little PR (including a ChangeLog entry) would be great!
