### ISSUE TITLE
Manage Conversations

### ISSUE THREAD

**Issue by Btibert3** [eddelbuettel/rpushbullet#56]
Is it possible to manage review and manage conversations with this package?  Via the methods listed, it's not clear if this is possible but I am also extremely new to the capabilities of Pushbullet.  It's clear that this package can push messages from our devices and get messages in a channel, but via the Web interface we can manage conversations and see some methods via the API docs.

Said differently, I know that we can push push a message via an email address, but is it possible to list friends and track the conversations so that I can programmatically reply?

**Comment by eddelbuettel** [comment]
I do not know, but I have no reason to suspect the exposed API hides this.  But before you nobody needed or wanted this, so it looks like we found someone new with an itch to scratch :)

**Comment by Btibert3** [comment]
Ok, I can/will poke around. Any tips on using the lego pieces inside the package that you have built?

**Comment by eddelbuettel** [comment]
It should be reasonably straightforward -- the package already deals with a token to given you access, and after than it "should" just be a metter of JSON requests.  At least for the simple(r) things, not sure how conversations would represented.  String blobs, maybe?

**Comment by eddelbuettel** [comment]
I guess we never followed-up on this so closing now.  

Feel free to reopen when there is "some action" (hey one can always hope...)
