### ISSUE TITLE
Error when getting the identifiers for the devices I’ve registered with pushbullet, Windows 11 machine

### ISSUE THREAD

**Issue by nikosGeography** [eddelbuettel/rpushbullet#69]
Hi, I am trying to install the RPushbullet package on a Windows 11 machine. I am using R 4.1.1. I have created the json file and I placed it in the $HOME directory. But when I am running the command fromJSON(pbGetDevices())$devices[,c("iden", "nickname")] I am receiving the following error: Error: Argument 'txt' must be a JSON string, URL or file. The .rpushbullet.json file in my $HOME directory has the correct API key, devices and names written in it. When I installed the package on a Windows 10 machine I encountered no problems. Here is the code:

```
install.packages("RPushbullet")
library(RPushbullet)
library(jsonlite)

#here is created the json file using Sys.getenv("HOME") in order to find the $HOME directory. The json file has the following code written:
{
    "key": "my api",
    "devices": [],
    "names": []
}

pbSetup()

#after excecuting the pbSetup(), the key, devices and names filled with the correct text

fromJSON(pbGetDevices())$devices[,c("iden", "nickname")] #here I am getting the error mentioned in the description
```
Any ideas? Thanks

**Comment by eddelbuettel** [comment]
Ok, but a) _why_ do you want to that and b) why do you expect this to work?

I can reproduce that `fromJSON(pbGetDevices())$devices[,c("iden", "nickname")]` fails -- but maybe that is a conceptual error? 

If you break it down and look at just `pbGetDevices())$devices[,c("iden", "nickname")` just a regular data.frame subset to the two columns you request -- no JSON anywhere, the package works and the error is "simply" in passing non-JSON data to a JSON parser.

**Comment by eddelbuettel** [comment]
Sometimes it _is_ the small stuff.  The package is stable, the API under it is stable so things shoud just work.  Good luck!

**Comment by nikosGeography** [comment]
Yes, I apologize for my question. It is truly a great package! Keep up the good work!
